---
title: '2021-09-07 Formula 1 Races'
author: "Statrozphere.org"
date: "9/7/2021"
output: html_document
---

# Tidy Tuesday 07-09-2021

## Preparation {.tabset}
### Library
```{r library, message=FALSE, warning=FALSE}
library(tidytuesdayR)
library(tidyverse)
```
### Checking Available Dataset
```{r}
tt_available()
```

### Downloading TT dataset
```{r download_data, eval=FALSE}
tt_data <- tt_load("2021-09-07")
```

### Individual data
```{r}
circuit <- tt_data$circuits
constructor_results <- tt_data$constructor_results
constructor_standings <- tt_data$constructor_standings
driver_standings <- tt_data$driver_standings
driver <- tt_data$drivers
lap_times <- tt_data$lap_times
pit_stops <- tt_data$pit_stops
qualifying <- tt_data$qualifying
races <- tt_data$races
results <- tt_data$results
seasons <- tt_data$seasons
status <- tt_data$status
```

### Join Table
```{r}
#driver_race_circuit <- driver_standings %>%
#  left_join(driver, by = "driverId") %>%
#  left_join(races, by = "raceId") %>% 
#  left_join(circuit, by = "circuitId")
```

```{r}
pitstops_bydrive <- pit_stops %>%
  left_join(driver, by = "driverId") %>%
  left_join(races, by = "raceId")
```

### Select Data
```{r}
time_driver <- pitstops_bydrive %>% 
  select(driverRef, milliseconds, year, name) %>%
  filter(name == "Malaysian Grand Prix") %>%
  select(-name) %>%
  group_by(driverRef, year) %>%
  summarise(milliseconds = mean(milliseconds), .groups="keep") %>%
  #ungroup(driverRef) %>%
  #distinct(milliseconds, .keep_all = TRUE)
  ungroup(year) %>%
  filter(milliseconds < 53000) %>%
  mutate(cumulative = cumsum(milliseconds)) %>%
  filter(driverRef %in% c("hamilton", "alonso", "vettel", "schumaker", "bottas", "hulkenberg", "massa", "perez", "rosberg", "raikkonen"))

pitstop_time <- time_driver %>%
  ggplot(aes(x=year, y=milliseconds)) +
  geom_line(aes(group = driverRef, color = driverRef)) +
  theme_minimal()

  
pitstop_time
```
## Who's Fastest on each circuits?
```{r}
fastest <- races %>%
  left_join(y=circuit, by="circuitId") %>%
  left_join(y=lap_times, by=c("raceId.x" = "raceId")) %>%
  group_by(circuitId) %>%
  summarise(fastest = min(milliseconds, na.rm=TRUE)) %>%
  filter(fastest != Inf)

fast_circuit <- fastest %>%
  left_join(circuit, by="circuitId") %>%
  distinct(circuitId, .keep_all = TRUE) %>%
  select(c("circuitId", "fastest", "name.x", "location"))

lap_only <- lap_times %>%
  select("milliseconds", "driverId")

who <- fast_circuit %>%
  inner_join(lap_only, by=c("fastest" = "milliseconds"))
```





























